### ISSUE TITLE
Which ReefWingMSP version is required

### ISSUE THREAD

**Issue by kilrah** [ramiss/arduino_DJI_03_RC_ARM#1]
With current 2.0.0 the MSP_STATUS_EX used in line 88 is undefined

![image](https://user-images.githubusercontent.com/6065069/211042371-5320835a-f1ef-47ba-bae0-fb936e22f0b0.png)

**Comment by ramiss** [comment]
Thanks for this.  I realized I edited my own ReefWing library at one point.  I have fixed this sketch to now work with the latest ReefWing library by adding the following line:

`#define MSP_STATUS_EX            150   //out message		 For OSD ‘Fly mode', For OSD ‘Disarmed’`

**Comment by kilrah** [comment]
Confirmed working, thanks!
