### ISSUE TITLE
XIAO Error when flashing

### ISSUE THREAD

**Issue by PPPRY** [ramiss/arduino_DJI_03_RC_ARM#13]
Compilation error: 'LED_BUILTIN' was not declared in this scope, First time writing the code to the board. I had no issue writing it to a nano board a few months ago. New to this, can I get a little help, please?!

**Comment by ramiss** [comment]
The XIAO ESP32C3 is s different board to the original XIAO Seeeduino and will need the code modified.  You can try commenting out the LED lines as they aren't critical.

**Comment by PPPRY** [comment]
<img width="613" alt="image" src="https://github.com/ramiss/arduino_DJI_03_RC_ARM/assets/139185398/97625975-9cb1-481c-b680-25a83330c8da">
So I switched the board over to seeedstudio. This is what I got https://www.amazon.com/Seeeduino-Smallest-Microcontroller-Interfaces-Compatible/dp/B08745JBRP/ref=sr_1_3?crid=1CD5QESFC58XJ&keywords=seeeduino+xiao&qid=1689388043&sprefix=seee%2Caps%2C176&sr=8-3

**Comment by ramiss** [comment]
You misunderstand. The board needs to match. The code is not designed for the board you have.

**Comment by PPPRY** [comment]
> The XIAO ESP32C3 is s different board to the original XIAO Seeeduino and will need the code modified. You can try commenting out the LED lines as they aren't critical.
https://www.seeedstudio.com/Seeeduino-XIAO-3Pcs-p-4546.html This is the original correct?

**Comment by ramiss** [comment]
Correct,  with the SAMD21

**Comment by PPPRY** [comment]
> Correct, with the SAMD21

So the last error was what I got after switching the board configuration over. The screen shot above. No longer the led error.

**Comment by ramiss** [comment]
Did you add the Seeed Studio XIAO SAMD21 board in Arduino IDE? 

https://wiki.seeedstudio.com/Seeeduino-XIAO/

**Comment by PPPRY** [comment]
Yes, bottom left of the screen shot above has the correct board?  #error MCU has no such a register
<img width="411" alt="image" src="https://github.com/ramiss/arduino_DJI_03_RC_ARM/assets/139185398/84236c13-7c1e-41fc-8b4a-abb985e85f5e">

**Comment by ramiss** [comment]
I wonder if you are not on the latest version of this code as it was significantly overhauled and the prior version was build for the Nano. After that,  make sure you are on the latest version of the Arduino IDE as well as making sure your libraries are up to date.
