### ISSUE TITLE
Please help error

### ISSUE THREAD

**Issue by Logan988** [ramiss/arduino_DJI_03_RC_ARM#14]
I am getting a error code of #include "MSP.h"

**Comment by ramiss** [comment]
> I am getting a error code of #include "MSP.h"

That usually means you didn't download all of the files.

**Comment by Logan988** [comment]
Ok, I deleted everything and tried downloading them in the zip folder again
then installing them. They work now thanks so much

**Comment by ramiss** [comment]
Excellent!
