### ISSUE TITLE
Error in compilation

### ISSUE THREAD

**Issue by 3dstaff** [ramiss/arduino_DJI_03_RC_ARM#16]
Hello, i try to compile the code for my original seeeduino samd21 but i get this errors in the image below, can you help please, my config seems ok. It's a matter of compiling, the device works with other sketches.
<a target="_blank" href="https://imageupload.io/rRyl5FyDearOQlO"><img  src="https://imageupload.io/ib/D5wc9CO7ei5jhZQ_1693315198.jpg" alt="Untitled-3.jpg"/></a>

**Comment by ramiss** [comment]
> Hello, i try to compile the code for my original seeeduino samd21 but i get this errors in the image below, can you help please, my config seems ok. It's a matter of compiling, the device works with other sketches. [![Untitled-3.jpg](https://camo.githubusercontent.com/aff765247e23f1a624b3b742533dff10508c671814a8a8384dd17648e4ec7660/68747470733a2f2f696d61676575706c6f61642e696f2f69622f4435776339434f376569356a685a515f313639333331353139382e6a7067)](https://imageupload.io/rRyl5FyDearOQlO)

Make sure you downloaded all code files.

**Comment by 3dstaff** [comment]
Solved compilation error, forgot to add the .cpp file, now i have an upload error: "SAM-BA operation failed"

**Comment by 3dstaff** [comment]
Write 36528 bytes to flash (571 pages)

[===                           ] 11% (64/571 pages)
[======                        ] 22% (128/571 pages)
[==========                    ] 33% (192/571 pages)
[=============                 ] 44% (256/571 pages)
[================              ] 56% (320/571 pages)
[====================          ] 67% (384/571 pages)
[=======================       ] 78% (448/571 pages)
[==========================    ] 89% (512/571 pages)
[==============================] 100% (571/571 pages)
SAM-BA operation failed

done in 0.251 seconds

Verify 36528 bytes of flash with checksum.
Verify successful
done in 0.065 seconds
CPU reset.
Failed uploading: uploading error: exit status 1

**Comment by 3dstaff** [comment]
All solved code uploaded, need solder now :), thanks for this project!
