### ISSUE TITLE
what si the purpose of that blue wire

### ISSUE THREAD

**Issue by lincoln2330** [ramiss/arduino_DJI_03_RC_ARM#17]
i am not sure if you have answered this to anyone before but can i know the purpose of that blue wire going to the Xiao pin 0. is it neccesary to use it even if i am using a seperate battery for dji o3 and Xiao? thanks!

**Comment by ramiss** [comment]
The blue wire is part of the "optional" voltage circuit.  It allows you to properly see your flight battery voltage on the OSD.
