### ISSUE TITLE
error message 

### ISSUE THREAD

**Issue by rcflyer69** [ramiss/arduino_DJI_03_RC_ARM#18]
i can't get this to work i need help

Desktop/arduino_DJI_03_RC_ARM-main/arduino_DJI_03_RC_ARM/arduino_DJI_03_RC_ARM.ino:28:10: fatal error: MSP.h: No such file or directory
 #include "MSP.h"

**Comment by ramiss** [comment]
Seems like you haven't downloaded all of the source files:
![261806529-0b575561-ca1b-4d3e-a452-9791597b5b56](https://github.com/ramiss/arduino_DJI_03_RC_ARM/assets/2555410/c06f08f2-f77d-4408-b050-21eedcedb595)

**Comment by rcflyer69** [comment]
now I'm getting this issue 

/Desktop/arduino_DJI_03_RC_ARM-main/arduino_DJI_03_RC_ARM/arduino_DJI_03_RC_ARM.ino:334:3: error: 'SerialUSB' was not declared in this scope
   SerialUSB.println("**********************************");

**Comment by ramiss** [comment]
Downgrade your board manager version to 1.7.9.  They changed something with SerialUSB that breaks the code after that.
