### ISSUE TITLE
O3 input levels are 3v3

### ISSUE THREAD

**Issue by Kisssys** [ramiss/arduino_DJI_03_RC_ARM#2]
I believe the Nano has 5 volt TTL and I believe the O3 shows 3v3 volt levels.  Maybe the inside is 5 volt tolerant but makes me nervous
to try this.
Cheers
Kisssys

**Comment by ramiss** [comment]
You could use 1k resistors on the signal wires to step down the voltage

**Comment by Kisssys** [comment]
Yes, you could, I just programmed a Seeduino XIAO board which is 3v3 volts
logic.
1/3 the size.
Cheers
Kisssys

**Comment by Slapjack30** [comment]
Hi @Kisssys,

Did you need to change a lot for the code, using the XIAO?

**Comment by Kisssys** [comment]
The code is attached for a XIAO Sam21.

I believe how the serial ports were defined was the main change.

Cheers
Kisssys

**Comment by Slapjack30** [comment]
thanks! 

and did you make the voltage divider too? on this XIAO? which resistors did you use to get it down to 3.3v?

TIA

**Comment by Kisssys** [comment]
That processor operates on 3v3 volts, so it's output is fine the way it is.

**Comment by Slapjack30** [comment]
i mean the voltage divider coming from Vbat (20V) to not 5V as in the example from Ramiss, but we need to get the 20V down to 3.3V for voltage info..

**Comment by Kisssys** [comment]
I saw no reason to read the voltage since the DJI displays it already.  I
removed that code.  You could add it and use a 39k/7.5k resistors for a max
of 20 volt would get you below 3.3 volts for the A2D
converter.

**Comment by Slapjack30** [comment]
Thanks a lot!!!

**Comment by Slapjack30** [comment]
could you share your code Kisssys? the one supplied doenst work with the XIAO...

**Comment by Kisssys** [comment]
The code was attached previously.

**Comment by Slapjack30** [comment]
i cant see your code in the project, could you be so kind to copy past your code? or send it to me? your code, if you have send yours to the owner, hasnt been updates yet in the master code...

TIA

**Comment by ramiss** [comment]
I've merged main into the master branch so you should see it now

**Comment by Slapjack30** [comment]
Awesome guys!!! thank a lot for your work! i hope to see the arm channel included in the XIAO version, because fixed wing flyers will power up the aircraft, do the pre flight checks, which can be a couple of minutes, and then take off... so plenty of time for the O3 unit to heat up, possibly causing problems. so arm channel would be great, but so far... awesome project!

cheers!

**Comment by ramiss** [comment]
I hope to get it added in the next week or so.  The big hurdle is that the XIAO logic is 3.3v and RC receiver PWM logic is 5v, so a logic level converter will be needed. Its more work than I had time for last weekend and I didn't want to wait to publish yesterday.
