### ISSUE TITLE
general questions 

### ISSUE THREAD

**Issue by abritten** [ramiss/arduino_DJI_03_RC_ARM#20]
Hi @ramiss I want to get this project started with a O3 and my fixed wing. I was trying this code on a Arduino Mega board but it seems to not be the right thing to do. I have a few questions below:

Will this code work on any know Arduino boards?
Is the Seeeduino board the SAMD21 version?
When you say to downgrade the board type to 1.7.9, I can only see the Sparkfun SAMD21, is that the correct selection or are there Seeeduino board libraries? (See picture attached)
Is it possible to re-add in a arming switch to switch the O3 back to low power mode?
I saw the 3.3V/5V issue, if I was to get this code working on a arduino, I would need to put a resistor between the Arduino TX and the O3 RX since there would be a 5V and 3.3V TTL?
 
<img width="768" alt="Screen Shot 2023-11-07 at 11 45 14 AM" src="https://github.com/ramiss/arduino_DJI_03_RC_ARM/assets/50151378/76da50dc-fd78-49a6-9507-cc40fe3f3ac1">

**Comment by mendberg** [comment]
This project (as is) is designed to run on Seeeduino XIAO SAMD21.

In Arduino IDE open **File / Preferences…** and add the following URL to **Additional boards manager URLs:**
https://files.seeedstudio.com/arduino/package_seeeduino_boards_index.json

![image](https://github.com/ramiss/arduino_DJI_03_RC_ARM/assets/22883877/a1a8d8ca-eb48-4af9-a075-6fa7eba86282)


You can then select & install _Seeed SAMD / 1.7.9_ in the **BOARDS MANAGER**

![image](https://github.com/ramiss/arduino_DJI_03_RC_ARM/assets/22883877/20782a6a-35bc-49ed-92b6-5382e6e7726d)

… compiling & uploading the code passed instantly. (So, now I have to solder… 😄)
