### ISSUE TITLE
Error uploading code

### ISSUE THREAD

**Issue by bsulley22** [ramiss/arduino_DJI_03_RC_ARM#21]
Totally new to this maybe I’m doing something wrong but any fix to this error 
![IMG_3188](https://github.com/ramiss/arduino_DJI_03_RC_ARM/assets/41933055/5a954254-b638-4a17-b20a-ad9b1212f734)

**Comment by ramiss** [comment]
You need to download all files into the same folder

**Comment by bsulley22** [comment]
Thanks for the reply where do I put that folder then?

**Comment by ramiss** [comment]
Anywhere you like.  Make sure you see the link under Step 4 on the Code page.
