### ISSUE TITLE
Sketch fails to upload, loses communication with COM when uploading

### ISSUE THREAD

**Issue by FNNCFPV** [ramiss/arduino_DJI_03_RC_ARM#27]
![20240224_045542](https://github.com/ramiss/arduino_DJI_03_RC_ARM/assets/100246791/e74f13b8-d5d3-4bbc-a13d-b70da052ff4b)
After a few seconds of trying to upload the board seems to lose communication with Arduino IDE. Led stops flashing and this error message pops up. Any suggestions would be greatly appreciated.

**Comment by ramiss** [comment]
From that screenshot, it looks like it never found the board at all.  You sure you are on the correct com port and have a good cable?
