### ISSUE TITLE
improve documentation please. No idea if this code is working. 

### ISSUE THREAD

**Issue by KPOPRC** [ramiss/arduino_DJI_03_RC_ARM#31]
The documentation on this is really poor. how do we know it's working? is there any documentation that states how we know if our o3 unit is seeing full power? as someone coming in blind. this doesn't explain much. even the arduino light doesn't really show any change from regular powered up state on power up. it also powers itself through the rx tx pins. arduino still powered on when unplugged from 5v.

**Comment by ramiss** [comment]
Thank you for pointing out that someone new might have an issue.  I'll think about how to improve this.   You will know that this is wording when your Air Unit Mbps jumps up to full (bottom right of the screen).  There is NO feedback from the air unit to the Arduino,  so setting a light or some other notification could give you a false positive. 

The Arduino being powered through the rx/tx is a side effect of how little power the Arduino requires.  While it works,  I don't recommend relying on it.
