### ISSUE TITLE
Error setting up 

### ISSUE THREAD

**Issue by Drvr4spd** [ramiss/arduino_DJI_03_RC_ARM#34]
Hi, 1st time trying to mess with this, I've downloaded the files, but in arduino I can not find any boards named seeduino xiao at all. I've tried to use arduino micro as the board says it's equivalent to that, but when I try to download the sketch into the card I get a compilation error: 'analogReadResolution' was not declared in this scope. Any help would he greatly appreciated,  thanks 
![17189234818833814646646949744085](https://github.com/ramiss/arduino_DJI_03_RC_ARM/assets/173415848/ae8dd55b-3cf2-4730-8cae-660b3798443a)

**Comment by ramiss** [comment]
The analogReadResolution line is specifically needed for the Seeduino and should be commented out for other boards.

Incidentally, here is how you install the Seeduino boards in the Arduino IDE, if needed:
[https://wiki.seeedstudio.com/Seeed_Arduino_Boards/](https://wiki.seeedstudio.com/Seeed_Arduino_Boards/)

**Comment by Drvr4spd** [comment]
Thank you, I'll run through that in the morning and load the seeduino boards, hopefully finally get it all straight and run it in my f18 this weekend at full power with the head tracker

**Comment by Drvr4spd** [comment]
thanks it worked perfect
