### ISSUE TITLE
Will it fit the air unit of the first version? I have such a de problem when connecting googles 2 and air unit

### ISSUE THREAD

**Issue by dom98111** [ramiss/arduino_DJI_03_RC_ARM#7]

**Comment by ramiss** [comment]
Although not tested,  the protocol is the same,  so it should work just fine with the other air units.

**Comment by druckgott** [comment]
Ok did you test it I'm. Also interested

**Comment by druckgott** [comment]
Its working with the old one

**Comment by ramiss** [comment]
I'm going to re-run full tests on the 03 this weekend. I  plan to report back on Sunday.

**Comment by ramiss** [comment]
Code is reworked with the XIAO Seeduino now (compatible logic voltage with DJI).  This should still absolutely work with the old air units.
