### ISSUE TITLE
Can you help me out with the voltrage reading?

### ISSUE THREAD

**Issue by Slapjack30** [ramiss/arduino_DJI_03_RC_ARM#8]
Hi Ramiss!

first off all, thanks for the awesome little thing you've made and shared, been looking for something like this for a long time.
but beeing the noob that i am when it comes to power and resistors, would you be so kind to point me in the right direction?

So first question, is the voltage reading pin used to display the voltage in the goggles (i have the goggles 2)? and if so:

I want to use this on a rc wing, with a battery pack which is 4S, so fully charged would be 16.8Volts, and drained it would be around 13.5V-ish... so what kind of resistors do i need? and what value should those be to get accurate reading? (what VOLT_DIVIDER should i use)

hope you have an answer, i would love to try this out!
Cheers!!

**Comment by ramiss** [comment]
See the new readme instructions (new resistor values to match the new code) and let me know if you still have questions.
