### ISSUE TITLE
My o3 isnt arming

### ISSUE THREAD

**Issue by JasonITB** [ramiss/arduino_DJI_03_RC_ARM#9]
I don't have a esc, throttle, or receiver connected. Only the o3 and the battery. I set bool always arm to true. Here's my wiring
[image](https://media.discordapp.net/attachments/1056499348776689686/1118088426940551188/IMG_3621.jpg?width=1003&height=753)

**Comment by JasonITB** [comment]
I realized that last image was bad here's a better version. My o3 firmware is V01.02.0000 if that helps. Could I please get some support on this? Thank you
[image](https://media.discordapp.net/attachments/1056499348776689686/1118089063522648104/IMG_3622.jpg?width=564&height=753)

**Comment by ramiss** [comment]
I'm currently out of the county with no access to test.  I'll be back next week and will figure this out for you and report back.  Sorry for the delay.

**Comment by ramiss** [comment]
I have reworked and tested the entire project for the much smaller XIAO Seeeduino, which is inherently 3.3v and compatible with the Air Unit.  It will now auto arm.  See Readme.
